repository:
  allow_auto_merge: true

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - documentation
          - verification
      enforce_admins: true
