spring.datasource.url=jdbc:h2:mem:testdb\nspring.datasource.driverClassName=org.h2.Driver\nspring.datasource.username=sa\nspring.datasource.password=
spring.session.store-type=none
spring.session.jdbc.initialize-schema=always
