server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/clinica
spring.datasource.username=clinica
spring.datasource.password=clinica
spring.datasource.driver-class-name=org.postgresql.Driver
spring.session.store-type=none
spring.session.jdbc.initialize-schema=always
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
management.health.ldap.enabled=false
