# Help URL Mappings to Diátaxis Artifacts
https\://docs.openclinica.com/3.1/study-setup=/docs/diataxis/tutorials/build_study.md
https\://docs.openclinica.com/3.1/rules=/docs/diataxis/references/rules.md
https\://docs.openclinica.com/diataxis/tutorials/build_study=/docs/diataxis/tutorials/build_study.md
https\://docs.openclinica.com/diataxis/how-to/import_data=/docs/diataxis/how-to/import_data.md
https\://docs.openclinica.com/diataxis/how-to/verify_import_rule=/docs/diataxis/how-to/verify_import_rule.md
https\://docs.openclinica.com/diataxis/how-to/generate_dataset_html=/docs/diataxis/how-to/generate_dataset_html.md
https\://docs.openclinica.com/diataxis/how-to/test_rules=/docs/diataxis/how-to/test_rules.md
https\://docs.openclinica.com/diataxis/how-to/extract_select_crf_and_group=/docs/diataxis/how-to/extract_select_crf_and_group.md
https\://docs.openclinica.com/diataxis/tutorials/participate_setup=/docs/diataxis/tutorials/participate_setup.md
https\://docs.openclinica.com/diataxis/tutorials/randomize_setup=/docs/diataxis/tutorials/randomize_setup.md
cookbook_index=/docs/diataxis/how-to/cookbook_index.md
cookbook_enrollment=/docs/diataxis/how-to/cookbook_enrollment.md
cookbook_scheduling=/docs/diataxis/how-to/cookbook_scheduling.md
cookbook_ingestion=/docs/diataxis/how-to/cookbook_ingestion.md
study_design_help=/docs/diataxis/how-to/cookbook_index.md
